### ISSUE TITLE
Move functionality to components

### ISSUE THREAD

**Issue by CptMeatball** [nsrosenqvist/october-plugin_cookieconsent#2]
In the current state this plugin is activated and run on install. The only way to disable this plugin's functionality is to disable the entire plugin in the `settings->update`` page of October. 

If functionality was to be moved to a component, developers can inject that component into the layout when properly set-up.

**Comment by nsrosenqvist** [comment]
This type of plugin would be site wide so it doesn't really make sense to force the user to add a component to each layout. Would it make more sense to add a "enabled" switch in the settings instead that's disabled by default and mention it on the plugin page?
